#!/usr/bin/env python3
"""
Stage 2 of 2 — responsive web derivatives.

Turns the lossless masters produced by crop-source.py into the AVIF / WebP /
JPEG ladder that public/*.html references, plus favicons and the social card.

    assets/masters/  +  assets/brand/   ->   public/img/**

Two rules make the "swap in the owner's originals tomorrow" story work:

  1. NEVER UPSCALE. Output widths are capped at the master's real width. Today's
     screenshot masters top out around 1290px, so that is where the ladder
     stops. The markup already asks for 1600/1920/2560; the moment a real
     high-resolution original lands in assets/sources.json, those rungs appear
     automatically with no markup change.

  2. STABLE FILENAMES. Paths are derived from the logical image ID, not from the
     camera filename, so the HTML never has to change.

Usage:  python3 scripts/build-images.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Pillow is required:  python3 -m pip install --user Pillow")

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
MASTERS = ASSETS / "masters"
BRAND = ASSETS / "brand"
OUT = ROOT / "public" / "img"

# Responsive ladder for photography. Rungs above the master's width are skipped.
PHOTO_WIDTHS = [480, 640, 960, 1280, 1600, 1920, 2560]
# Logos never render larger than ~260 CSS px, so 480 covers 2x DPR with room.
BRAND_WIDTHS = [120, 180, 240, 360, 480]

QUALITY = {"avif": 60, "webp": 80, "jpg": 82}


BOS_BLACK = (10, 10, 10)
BOS_YELLOW = (248, 184, 4)


def ladder(source_width: int, rungs: list[int], cap_only: bool = False) -> list[int]:
    """Widths to emit: every rung at or below the source. Never upscales.

    The source's own width is added as a top rung only when it is meaningfully
    larger than the highest standard rung -- within 5% is not worth a whole
    extra set of files (1290 next to 1280 buys nothing and costs a fifth of the
    payload). `cap_only` skips that entirely, which is what logos want: they
    never render above ~260 CSS px, so shipping the 1057px master is dead
    weight.
    """
    widths = [w for w in rungs if w <= source_width]
    if not widths:
        return [source_width]
    if not cap_only and source_width > widths[-1] * 1.05:
        widths.append(source_width)
    return sorted(set(widths))


def write_focus_css(data: dict) -> None:
    """Generate object-position rules from the manifest's focal points.

    Photographs are served at their natural aspect ratio and framed by CSS
    `object-fit: cover`, which preserves every available pixel of these
    low-resolution sources. This file is the bridge: the focal point lives in
    assets/sources.json next to the crop box, and lands here as CSS so the
    stylesheets never hard-code per-photo framing.

    GENERATED FILE -- do not edit by hand. Run `npm run images`.
    """
    lines = [
        "/* GENERATED by scripts/build-images.py -- do not edit.",
        " * Focal points come from assets/sources.json. Edit them there.",
        " *",
        " * Photos are served at their natural aspect ratio; the container sets",
        " * aspect-ratio and `object-fit: cover` crops to it. object-position",
        " * below keeps the subject in frame at every viewport. */",
        "",
    ]
    for key, spec in data["images"].items():
        if spec.get("alpha"):
            continue
        fx, fy = spec.get("focus", [0.5, 0.5])
        lines.append(
            f".img-{key} {{ object-position: {fx * 100:.4g}% {fy * 100:.4g}%; }}"
        )
    dest = ROOT / "public" / "css" / "image-focus.css"
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  {'image-focus.css':<22} {len(lines) - 6} focal-point rules")


def crop_to_aspect(img: Image.Image, aspect: float, focus: tuple[float, float]) -> Image.Image:
    """Crop to `aspect` (w/h), keeping `focus` in frame and clamped in-bounds."""
    w, h = img.size
    current = w / h
    if abs(current - aspect) < 0.005:
        return img
    if current > aspect:
        new_w, new_h = int(round(h * aspect)), h
    else:
        new_w, new_h = w, int(round(w / aspect))
    fx, fy = focus
    left = int(round(fx * w - new_w / 2))
    top = int(round(fy * h - new_h / 2))
    left = max(0, min(left, w - new_w))
    top = max(0, min(top, h - new_h))
    return img.crop((left, top, left + new_w, top + new_h))


def save_variant(img: Image.Image, path: Path, fmt: str) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "jpg":
        img.convert("RGB").save(
            path, "JPEG", quality=QUALITY["jpg"], optimize=True, progressive=True
        )
    elif fmt == "webp":
        img.save(path, "WEBP", quality=QUALITY["webp"], method=6)
    elif fmt == "avif":
        img.save(path, "AVIF", quality=QUALITY["avif"])
    elif fmt == "png":
        img.save(path, "PNG", optimize=True)
    else:
        raise ValueError(f"Unknown format: {fmt}")
    return path.stat().st_size


def build_one(key: str, spec: dict, report: list) -> None:
    is_brand = bool(spec.get("alpha"))
    src = (BRAND if is_brand else MASTERS) / f"{key}.png"
    if not src.exists():
        sys.exit(f"Master missing: {src}\nRun scripts/crop-source.py first.")

    img = Image.open(src)
    if is_brand:
        img = img.convert("RGBA")
    else:
        img = img.convert("RGB")

    aspect = spec.get("aspect")
    if aspect:
        focus = tuple(spec.get("focus", [0.5, 0.5]))
        img = crop_to_aspect(img, float(aspect), focus)

    formats = spec.get("formats") or ["avif", "webp", "jpg"]
    widths = ladder(
        img.size[0],
        BRAND_WIDTHS if is_brand else PHOTO_WIDTHS,
        cap_only=is_brand,
    )
    folder = OUT / spec.get("group", "misc")

    total = 0
    for w in widths:
        h = max(1, int(round(img.size[1] * w / img.size[0])))
        resized = img.resize((w, h), Image.LANCZOS)
        for fmt in formats:
            total += save_variant(resized, folder / f"{key}-{w}.{fmt}", fmt)

    report.append((key, img.size, widths, formats, total))
    print(
        f"  {key:<22} {img.size[0]}x{img.size[1]:<5} "
        f"widths={','.join(str(w) for w in widths):<28} "
        f"{'/'.join(formats):<16} {total / 1024:7.0f} KB"
    )


def build_social_card() -> None:
    """1200x630 share card: brand lockup on black with a yellow rule."""
    card = Image.new("RGB", (1200, 630), BOS_BLACK)
    logo = Image.open(BRAND / "bos-logo-horizontal.png").convert("RGBA")
    target_w = 880
    ratio = target_w / logo.size[0]
    logo = logo.resize((target_w, int(round(logo.size[1] * ratio))), Image.LANCZOS)
    card.paste(logo, ((1200 - logo.size[0]) // 2, (630 - logo.size[1]) // 2 - 18), logo)

    d = ImageDraw.Draw(card)
    d.rectangle([(0, 0), (1200, 7)], fill=BOS_YELLOW)
    d.rectangle([(460, 548), (740, 551)], fill=BOS_YELLOW)

    out = OUT / "og" / "og-card.jpg"
    out.parent.mkdir(parents=True, exist_ok=True)
    size = save_variant(card, out, "jpg")
    print(f"  {'og-card':<22} 1200x630                                      "
          f"            {size / 1024:7.0f} KB")


def build_favicons() -> None:
    """Square favicons cut from the real badge logo, on the brand black."""
    badge = Image.open(BRAND / "bos-logo-badge.png").convert("RGBA")
    for size in (32, 180, 192, 512):
        canvas = Image.new("RGBA", (size, size), BOS_BLACK + (255,))
        pad = int(size * 0.08)
        inner = size - pad * 2
        ratio = min(inner / badge.size[0], inner / badge.size[1])
        art = badge.resize(
            (max(1, int(badge.size[0] * ratio)), max(1, int(badge.size[1] * ratio))),
            Image.LANCZOS,
        )
        canvas.paste(
            art, ((size - art.size[0]) // 2, (size - art.size[1]) // 2), art
        )
        name = "apple-touch-icon.png" if size == 180 else f"favicon-{size}.png"
        dest = ROOT / "public" / name
        canvas.convert("RGB").save(dest, "PNG", optimize=True)
    print(f"  {'favicons':<22} 32 / 180 / 192 / 512")


def main() -> int:
    with (ASSETS / "sources.json").open(encoding="utf-8") as fh:
        data = json.load(fh)

    print("Building responsive derivatives into public/img/\n")
    report: list = []
    for key, spec in data["images"].items():
        build_one(key, spec, report)

    print()
    build_social_card()
    build_favicons()
    write_focus_css(data)

    shipped = sum(r[4] for r in report)
    capped = [r[0] for r in report if r[2][-1] < 1600 and "logo" not in r[0]]

    print(f"\n{'-' * 72}")
    print(f"Shipped image payload: {shipped / 1024 / 1024:.2f} MB across "
          f"{len(report)} logical images")
    if capped:
        print(
            "\nNOTE: these are capped by today's screenshot sources and will gain\n"
            "      1600/1920/2560 rungs automatically once real originals are\n"
            "      dropped into assets/sources.json:\n        "
            + "\n        ".join(capped)
        )
    print("\nDone. No image was upscaled.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
